services:
  postgres:
    container_name: decoupled-db
    build:
      context: postgres
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit@sha256:b004cc0672d0692f097ba8ab9e5956ae08eeafee3d0a6bf2ab239750101ac538
    container_name: decoupled-mailpit
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb@sha256:8f1ed22e10c9da0912169b98b62ddc54930dc39a5ae07b0f1354d2a93d44c6ed
    ports:
      - '8081:8081'
    links:
      - postgres:postgres
    env_file: .env
    environment:
      DATABASE_URL: postgres://$DB_USER:$DB_PASSWORD@postgres:5432/$DB_NAME
    depends_on:
      - postgres

  redis-1:
    image: redis:latest@sha256:f0957bcaa75fd58a9a1847c1f07caf370579196259d69ac07f2e27b5b389b021
    command: ['redis-server', '/etc/redis/redis.conf']
    ports:
      - 6379:6379
      - 16379:16379
    volumes:
      - redis-data:/root/redis
      - ./redis/node-1/conf/redis.conf:/etc/redis/redis.conf

volumes:
  db-data:
  redis-data:
